# Display.
title: "JavaScript versus Research Computing"
subtitle: "A Brief Guide for Those Who Regret That This Has Become Necessary"
author: "Greg Wilson"
copyrightyear: "2017-18"

# Code highlighting.
highlighter: rouge

# GitHub repository.
repository: https://github.com/gvwilson/js-vs-rc/

# Pages that aren't in collections.
toplevel:
- permalink: /license/
  title: "License"
- permalink: /conduct/
  title: "Code of Conduct"
- permalink: /contributing/
  title: "Contributing"

# Collections.
collections:
  sections:
    output: true
