# Display.
title: "JavaScript versus Data Science"
subtitle: "A Brief Guide for Those Who Regret That This Has Become Necessary"
author: "Greg Wilson"
copyrightyear: "2018"
repo: https://github.com/gvwilson/js-vs-ds/
email: gvwilson@third-bit.com
website: "https://gvwilson.github.io/js-vs-ds/"
isbn: "000-0-0000000-0"
purchase: ""
paypal: ""

# Theme color.
background: "#f0e0f0"

# Jekyll settings.
highlighter: rouge
plugins:
- "jekyll-redirect-from"

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- misc
- requirements.txt
- "tex_*"

# Markers in generated files.
marker:
  start: "<!-- main start -->"
  end: "<!-- main end -->"
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_en:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_en
    values:
      language: "en"
      layout: "default"

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /core/
  - /callbacks/
  - /htmlcss/
  - /display/
  - /oop/
  - /interactive/
  - /server/
  - /testing/
  - /database/
  - /viz/
  - /capstone/
  - /finale/
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /gloss/
  - /legacy/

# Translations by language.
translations:
  en:
    generated: "Last generated"
    questions: "Questions"
    keypoints: "Key Points"
    singlepage: "Single page version"
