# Display.
title: "JavaScript versus Data Science"
subtitle: "A Brief Guide for Those Who Regret That This Has Become Necessary"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/software-tools-in-javascript/js-vs-ds/"
email: "gvwilson@third-bit.com"
website: "https://software-tools-in-javascript.github.io/js-vs-ds/"
isbn: "000-0-0000000-0"
purchase: ""
paypal: ""

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /basics/
  - /callbacks/
  - /oop/
  - /htmlcss/
  - /pages/
  - /dynamic/
  - /vis/
  - /promises/
  - /interactive/
  - /dataman/
  - /server/
  - /testing/
  - /capstone/
  - /finale/
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /contributing/
  - /gloss/
  - /keypoints/
  - /legacy/
  - /regexp/
  - /logging/
  - /db/
  - /extensible/

# Theme color.
background: "#e8f8e8"

# Data source.
datasource: "https://figshare.com/articles/Portal_Project_Teaching_Database/1314459"

# Jekyll settings.
highlighter: rouge
plugins:
- "jekyll-redirect-from"

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- misc
- node_modules
- requirements.txt
- tex

# Markers in generated files.
marker:
  crossref: "let CROSSREF="

# Collections: one for lessons and one for extras for each language suffix.
collections:
  en:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: en
    values:
      language: "en"
      layout: "default"

# Translations by language.
translations:
  en:
    generated: "Last generated"
    questions: "Questions"
    keypoints: "Key Points"
    singlepage: "Single page version"
